[book]
title = "Journal101"
authors = ["Anindya Shiddhartha"]
description = "de-facto journal-turned-book for the ugliest thoughts I had during my CS degree"
language = "en"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/hitblast/journal101"

[output.html.search]
limit-results = 15

[preprocessor.gitinfo]
enable = true

header = false   # default: false
footer = true    # default: true

font-size   = "0.9em"
separator   = " • "
date-format = "%Y-%m-%d"
time-format = "%H:%M:%S"
branch      = "master"
hyperlink   = true  # make hash/branch clickable when possible

timezone = "local"   # "local" (default) | "utc" | "source" | "fixed:+02:00"

[preprocessor.gitinfo.message]
footer = "<hr>Built {{date}}{{sep}}commit: {{hash}}<br>Licensed under <a href='https://creativecommons.org/licenses/by-sa/4.0/'>CC BY-SA 4.0</a>"
